- name: configure locales
  copy: src=i18n dest=/etc/sysconfig/i18n

- name: change root gecos
  user: name=root comment=root-{{ ansible_hostname }}

- name: install basic packages
  yum: name={{ item }} state=installed
  with_items:
    - diffutils
    - bash-completion
    - file
    - iproute
    - less
    - lsof
    - man
    - openssh-server
    - patch
    - psmisc
    - rsync
    - screen
    - sudo
    - tar
    - vim-enhanced
    - wget

- name: install additional packages
  yum: name={{ item }} state=installed
  with_items: '{{ extra_packages }}'
  when: extra_packages

- name: Install EPEL (CentOS)
  yum: name=epel-release state=installed
  when: ansible_distribution == 'CentOS'

- name: enable SSH
  service: name={{ item }} state=started
  with_items:
    - sshd

- name: disable SELinux
  lineinfile: dest=/etc/sysconfig/selinux regexp="^#?SELINUX" line="SELINUX=disabled"
  when: ansible_virtualization_role=="host"

- name: enable UTC clock
  lineinfile: regexp="^#?UTC" line="UTC=true" dest=/etc/sysconfig/clock create=yes

- name: install packages for hosts
  yum: name={{ item }} state=installed
  when: ansible_virtualization_role=="host"
  with_items:
    - ntp
    - acpid
    - tcpdump

- name: remove unwanted packages
  yum: name={{ item }} state=absent
  with_items:
    - locate
    - mlocate
    - nano

- name: copy configuration files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: "better-profile",         dest: "/etc/profile.d/basic.sh"}
    - {src: "bashprofile-root-rhel", dest: "/root/.bash_profile"}
    - {src: "vimrc-local",           dest: "/etc/vimrc"}

